language: python
sudo: false
notifications:
  email: false

python:
- '3.6'
before_install:
- sudo apt-get -y install gcc libattr1-dev
script:
  - make check TEST_TARGET=./tests/unit/
  - make check TEST_TARGET=./tests/integration/
deploy:
  provider: pypi

after_deploy:
- make rpm
